library(tidyverse)
library(targets)
library(tarchetypes)
source("R/functions.R")
tar_option_set(
  packages = c("car","cowplot","dplyr","fastDummies","ggcorrplot","ggforce",
               "ggraph","ggplot2","haven","igraph","kableExtra","lavaan","lme4",
               "lmerTest","ltm","mice","papaja","psych","readr","semTools",
               "stringr")
)
# pipeline
list(
  # files
  tar_target(fileData, "data/NZAVS Longitudinal SPSS Base Dataset.sav", format = "file"),
  # load data
  tar_target(dFull, loadData(fileData)),
  # filter data to participants who completed both waves
  tar_target(d, filterData(dFull)),
  # plot timeline
  tar_target(timeline, plotTimeline(d)),
  # make item table
  tar_target(itemTable, makeItemTable()),
  # plot proportion observed data
  tar_target(plotObs, plotPropObserved(d)),
  # test for selection bias
  tar_target(biasTable, getBiasTable(dFull, 
                                     variables = c("egame.TG1.T10","egame.TG2.T10",
                                                   "egame.PGG.T10","egame.DG.T10","T10.SDO",
                                                   "Issue.IncomeRedistribution.T10",
                                                   "IncomeAttribution.T10",
                                                   "Pol.SupNational.T10"))),
  # test for differences between waves
  tar_target(diffTable, getDiffTable(d, games = c("TG1","TG2","PGG","DG"))),
  # plot correlations between games
  tar_target(plotCors, plotCorrelations(d)),
  # reliability
  tar_target(reliability1, omega(d[,c("egame.TG1.T10","egame.TG2.T10",
                                      "egame.DG.T10","egame.PGG.T10")])),
  tar_target(reliability2, omega(d[,c("egame.TG1.T11","egame.TG2.T11",
                                      "egame.DG.T11","egame.PGG.T11")])),
  # impute data
  tar_target(dM, imputeData(d)),
  # plot imputation model
  tar_target(plotImputation, plotImpModel(dM)),
  # fit cfa
  tar_target(cfa1, fitCFA1(d)),
  # fit sem
  tar_target(sem1, fitSEM1(dM)),
  tar_target(plotSem1, plotCoopSDO(dM)),
  # measurement invariance across waves
  tar_target(configMI, fitMI(d, type = "config")),
  tar_target(metricMI, fitMI(d, type = "metric")),
  tar_target(scalarMI, fitMI(d, type = "scalar")),
  tar_target(strictMI, fitMI(d, type = "strict")),
  tar_target(tableCompareMI, getComparisonTable(configMI, metricMI, scalarMI, strictMI)),
  # setup cross-lagged panel models
  tar_target(clpmControls, c(
    "Age.T10.c", "Gender.T10", "EthnicCats.T10_Asian + EthnicCats.T10_Maori + EthnicCats.T10_Pacific",
    "NZREG.T10", "NZSEI13.T10", "NZDep.2013.T10", "Religious.T10", "T10.RWA",
    "T10.EXTRAVERSION", "T10.AGREEABLENESS", "T10.CONSCIENTIOUSNESS", 
    "T10.NEUROTICISM", "T10.OPENNESS", "T10.HONESTY_HUMILITY", "T10.NARCISSISM",
    "Age.T10.c + Gender.T10 + EthnicCats.T10_Asian + EthnicCats.T10_Maori + EthnicCats.T10_Pacific + NZREG.T10 + NZSEI13.T10 + NZDep.2013.T10 + Religious.T10 + T10.RWA + T10.EXTRAVERSION + T10.AGREEABLENESS + T10.CONSCIENTIOUSNESS + T10.NEUROTICISM + T10.OPENNESS + T10.HONESTY_HUMILITY + T10.NARCISSISM"
    )),
  tar_target(clpmOrdered, list(
    c(paste0("egame.TG1.T1", 0:1)),
    c(paste0("egame.TG1.T1", 0:1), paste0("Issue.IncomeRedistribution.T1", 0:1)),
    c(paste0("egame.TG1.T1", 0:1), paste0("IncomeAttribution.T1", 0:1)),
    c(paste0("egame.TG1.T1", 0:1), paste0("Pol.SupNational.T1", 0:1))
  )),
  # run cross-lagged panel models with imputed data
  # with mean sdo
  tar_target(clpm1.01a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]])),
  tar_target(clpm1.02a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[01])),
  tar_target(clpm1.03a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[02])),
  tar_target(clpm1.04a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[03])),
  tar_target(clpm1.05a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[04])),
  tar_target(clpm1.06a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[05])),
  tar_target(clpm1.07a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[06])),
  tar_target(clpm1.08a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[07])),
  tar_target(clpm1.09a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[08])),
  tar_target(clpm1.10a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[09])),
  tar_target(clpm1.11a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[10])),
  tar_target(clpm1.12a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[11])),
  tar_target(clpm1.13a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[12])),
  tar_target(clpm1.14a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[13])),
  tar_target(clpm1.15a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[14])),
  tar_target(clpm1.16a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[15])),
  tar_target(clpm1.17a, fitCLPM(dM, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[16])),
  # with income redistribution
  tar_target(clpm2.01a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]])),
  tar_target(clpm2.02a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[01])),
  tar_target(clpm2.03a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[02])),
  tar_target(clpm2.04a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[03])),
  tar_target(clpm2.05a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[04])),
  tar_target(clpm2.06a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[05])),
  tar_target(clpm2.07a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[06])),
  tar_target(clpm2.08a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[07])),
  tar_target(clpm2.09a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[08])),
  tar_target(clpm2.10a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[09])),
  tar_target(clpm2.11a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[10])),
  tar_target(clpm2.12a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[11])),
  tar_target(clpm2.13a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[12])),
  tar_target(clpm2.14a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[13])),
  tar_target(clpm2.15a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[14])),
  tar_target(clpm2.16a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[15])),
  tar_target(clpm2.17a, fitCLPM(dM, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[16])),
  # with income attribution
  tar_target(clpm3.01a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]])),
  tar_target(clpm3.02a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[01])),
  tar_target(clpm3.03a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[02])),
  tar_target(clpm3.04a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[03])),
  tar_target(clpm3.05a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[04])),
  tar_target(clpm3.06a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[05])),
  tar_target(clpm3.07a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[06])),
  tar_target(clpm3.08a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[07])),
  tar_target(clpm3.09a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[08])),
  tar_target(clpm3.10a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[09])),
  tar_target(clpm3.11a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[10])),
  tar_target(clpm3.12a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[11])),
  tar_target(clpm3.13a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[12])),
  tar_target(clpm3.14a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[13])),
  tar_target(clpm3.15a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[14])),
  tar_target(clpm3.16a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[15])),
  tar_target(clpm3.17a, fitCLPM(dM, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[16])),
  # with National party support
  tar_target(clpm4.01a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]])),
  tar_target(clpm4.02a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[01])),
  tar_target(clpm4.03a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[02])),
  tar_target(clpm4.04a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[03])),
  tar_target(clpm4.05a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[04])),
  tar_target(clpm4.06a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[05])),
  tar_target(clpm4.07a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[06])),
  tar_target(clpm4.08a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[07])),
  tar_target(clpm4.09a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[08])),
  tar_target(clpm4.10a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[09])),
  tar_target(clpm4.11a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[10])),
  tar_target(clpm4.12a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[11])),
  tar_target(clpm4.13a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[12])),
  tar_target(clpm4.14a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[13])),
  tar_target(clpm4.15a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[14])),
  tar_target(clpm4.16a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[15])),
  tar_target(clpm4.17a, fitCLPM(dM, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[16])),
  # run cross-lagged panel models with listwise-deleted data
  # with mean sdo
  tar_target(clpm1.01b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]])),
  tar_target(clpm1.02b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[01])),
  tar_target(clpm1.03b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[02])),
  tar_target(clpm1.04b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[03])),
  tar_target(clpm1.05b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[04])),
  tar_target(clpm1.06b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[05])),
  tar_target(clpm1.07b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[06])),
  tar_target(clpm1.08b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[07])),
  tar_target(clpm1.09b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[08])),
  tar_target(clpm1.10b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[09])),
  tar_target(clpm1.11b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[10])),
  tar_target(clpm1.12b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[11])),
  tar_target(clpm1.13b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[12])),
  tar_target(clpm1.14b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[13])),
  tar_target(clpm1.15b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[14])),
  tar_target(clpm1.16b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[15])),
  tar_target(clpm1.17b, fitCLPM(d, var1 = "T10.SDO", var2 = "T11.SDO", ordered = clpmOrdered[[1]], controls = clpmControls[16])),
  # with income redistribution
  tar_target(clpm2.01b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]])),
  tar_target(clpm2.02b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[01])),
  tar_target(clpm2.03b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[02])),
  tar_target(clpm2.04b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[03])),
  tar_target(clpm2.05b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[04])),
  tar_target(clpm2.06b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[05])),
  tar_target(clpm2.07b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[06])),
  tar_target(clpm2.08b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[07])),
  tar_target(clpm2.09b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[08])),
  tar_target(clpm2.10b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[09])),
  tar_target(clpm2.11b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[10])),
  tar_target(clpm2.12b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[11])),
  tar_target(clpm2.13b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[12])),
  tar_target(clpm2.14b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[13])),
  tar_target(clpm2.15b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[14])),
  tar_target(clpm2.16b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[15])),
  tar_target(clpm2.17b, fitCLPM(d, var1 = "Issue.IncomeRedistribution.T10", var2 = "Issue.IncomeRedistribution.T11", ordered = clpmOrdered[[2]], controls = clpmControls[16])),
  # with income attribution
  tar_target(clpm3.01b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]])),
  tar_target(clpm3.02b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[01])),
  tar_target(clpm3.03b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[02])),
  tar_target(clpm3.04b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[03])),
  tar_target(clpm3.05b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[04])),
  tar_target(clpm3.06b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[05])),
  tar_target(clpm3.07b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[06])),
  tar_target(clpm3.08b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[07])),
  tar_target(clpm3.09b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[08])),
  tar_target(clpm3.10b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[09])),
  tar_target(clpm3.11b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[10])),
  tar_target(clpm3.12b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[11])),
  tar_target(clpm3.13b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[12])),
  tar_target(clpm3.14b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[13])),
  tar_target(clpm3.15b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[14])),
  tar_target(clpm3.16b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[15])),
  tar_target(clpm3.17b, fitCLPM(d, var1 = "IncomeAttribution.T10", var2 = "IncomeAttribution.T11", ordered = clpmOrdered[[3]], controls = clpmControls[16])),
  # with National party support
  tar_target(clpm4.01b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]])),
  tar_target(clpm4.02b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[01])),
  tar_target(clpm4.03b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[02])),
  tar_target(clpm4.04b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[03])),
  tar_target(clpm4.05b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[04])),
  tar_target(clpm4.06b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[05])),
  tar_target(clpm4.07b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[06])),
  tar_target(clpm4.08b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[07])),
  tar_target(clpm4.09b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[08])),
  tar_target(clpm4.10b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[09])),
  tar_target(clpm4.11b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[10])),
  tar_target(clpm4.12b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[11])),
  tar_target(clpm4.13b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[12])),
  tar_target(clpm4.14b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[13])),
  tar_target(clpm4.15b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[14])),
  tar_target(clpm4.16b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[15])),
  tar_target(clpm4.17b, fitCLPM(d, var1 = "Pol.SupNational.T10", var2 = "Pol.SupNational.T11", ordered = clpmOrdered[[4]], controls = clpmControls[16])),
  # multigroup analyses split by gender
  tar_target(dM_gender, dMfactor(dM, "Gender.T10")),
  tar_target(clpm1_gender, fitCLPMSplit(dM_gender, var1 = "T10.SDO", var2 = "T11.SDO", ordered = c(paste0("egame.TG1.T1", 0:1)), group = "Gender.T10")),
  tar_target(dM_ethnic, dMfactor(dM, "EthnicCats.T10")),
  tar_target(clpm1_ethnic, fitCLPMSplit(dM_ethnic, var1 = "T10.SDO", var2 = "T11.SDO", ordered = c(paste0("egame.TG1.T1", 0:1)), group = "EthnicCats.T10")),
  # figures
  # models with imputed data
  tar_target(clpmPlotA_SDO, drawCLPMFigure(
    list(clpm1.01a, clpm1.02a, clpm1.03a, clpm1.04a, clpm1.05a,
         clpm1.06a, clpm1.07a, clpm1.08a, clpm1.09a, clpm1.10a,
         clpm1.11a, clpm1.12a, clpm1.13a, clpm1.14a, clpm1.15a,
         clpm1.16a, clpm1.17a), 
    "T10.SDO", "T11.SDO", "SDO", -0.4, 0.3,
    "figures/clpmPlot_SDO_imputed.pdf")),
  tar_target(clpmPlotA_IncRed, drawCLPMFigure(
    list(clpm2.01a, clpm2.02a, clpm2.03a, clpm2.04a, clpm2.05a,
         clpm2.06a, clpm2.07a, clpm2.08a, clpm2.09a, clpm2.10a,
         clpm2.11a, clpm2.12a, clpm2.13a, clpm2.14a, clpm2.15a,
         clpm2.16a, clpm2.17a),
    "Issue.IncomeRedistribution.T10", "Issue.IncomeRedistribution.T11", "IncRed", -0.2, 0.4,
    "figures/clpmPlot_IncRed_imputed.pdf")),
  tar_target(clpmPlotA_IncAtt, drawCLPMFigure(
    list(clpm3.01a, clpm3.02a, clpm3.03a, clpm3.04a, clpm3.05a,
         clpm3.06a, clpm3.07a, clpm3.08a, clpm3.09a, clpm3.10a,
         clpm3.11a, clpm3.12a, clpm3.13a, clpm3.14a, clpm3.15a,
         clpm3.16a, clpm3.17a),
    "IncomeAttribution.T10", "IncomeAttribution.T11", "IncAtt", -0.4, 0.3,
    "figures/clpmPlot_IncAtt_imputed.pdf")),
  tar_target(clpmPlotA_PolNat, drawCLPMFigure(
    list(clpm4.01a, clpm4.02a, clpm4.03a, clpm4.04a, clpm4.05a,
         clpm4.06a, clpm4.07a, clpm4.08a, clpm4.09a, clpm4.10a,
         clpm4.11a, clpm4.12a, clpm4.13a, clpm4.14a, clpm4.15a,
         clpm4.16a, clpm4.17a),
    "Pol.SupNational.T10", "Pol.SupNational.T11", "PolNat", -0.25, 0.5,
    "figures/clpmPlot_PolNat_imputed.pdf")),
  # models with listwise-deleted data
  tar_target(clpmPlotB_SDO, drawCLPMFigure(
    list(clpm1.01b, clpm1.02b, clpm1.03b, clpm1.04b, clpm1.05b,
         clpm1.06b, clpm1.07b, clpm1.08b, clpm1.09b, clpm1.10b,
         clpm1.11b, clpm1.12b, clpm1.13b, clpm1.14b, clpm1.15b,
         clpm1.16b, clpm1.17b), 
    "T10.SDO", "T11.SDO", "SDO", -0.4, 0.3,
    "figures/clpmPlot_SDO_listwise.pdf")),
  tar_target(clpmPlotB_IncRed, drawCLPMFigure(
    list(clpm2.01b, clpm2.02b, clpm2.03b, clpm2.04b, clpm2.05b,
         clpm2.06b, clpm2.07b, clpm2.08b, clpm2.09b, clpm2.10b,
         clpm2.11b, clpm2.12b, clpm2.13b, clpm2.14b, clpm2.15b,
         clpm2.16b, clpm2.17b),
    "Issue.IncomeRedistribution.T10", "Issue.IncomeRedistribution.T11", "IncRed", -0.2, 0.4,
    "figures/clpmPlot_IncRed_listwise.pdf")),
  tar_target(clpmPlotB_IncAtt, drawCLPMFigure(
    list(clpm3.01b, clpm3.02b, clpm3.03b, clpm3.04b, clpm3.05b,
         clpm3.06b, clpm3.07b, clpm3.08b, clpm3.09b, clpm3.10b,
         clpm3.11b, clpm3.12b, clpm3.13b, clpm3.14b, clpm3.15b,
         clpm3.16b, clpm3.17b),
    "IncomeAttribution.T10", "IncomeAttribution.T11", "IncAtt", -0.4, 0.3,
    "figures/clpmPlot_IncAtt_listwise.pdf")),
  tar_target(clpmPlotB_PolNat, drawCLPMFigure(
    list(clpm4.01b, clpm4.02b, clpm4.03b, clpm4.04b, clpm4.05b,
         clpm4.06b, clpm4.07b, clpm4.08b, clpm4.09b, clpm4.10b,
         clpm4.11b, clpm4.12b, clpm4.13b, clpm4.14b, clpm4.15b,
         clpm4.16b, clpm4.17b),
    "Pol.SupNational.T10", "Pol.SupNational.T11", "PolNat", -0.25, 0.5,
    "figures/clpmPlot_PolNat_listwise.pdf")),
  # render manuscript
  tar_render(manuscript, "manuscript.Rmd"),
  # print session info for reproducibility
  tar_target(sessionInfo, writeLines(capture.output(sessionInfo()), "sessionInfo.txt"))
)