# item table
makeItemTable <- function() {
  tibble(
    Item = 
      c("SDO1", "SDO2", "SDO3", "SDO4 (reversed)", "SDO5 (reversed)", "SDO6 (reversed)", 
        "RWA1", "RWA2", "RWA3", "RWA4 (reversed)", "RWA5 (reversed)", "RWA6 (reversed)",
        "Income redistribution", "Income attribution", "Support for National Party", "Age", 
        "Gender", "Ethnicity", "Education level", "Socio-economic status", "Local deprivation",
        "Religiosity", "Extraversion1", "Extraversion2 (reversed)", "Extraversion3 (reversed)", 
        "Extraversion4", "Agreeableness1", "Agreeableness2 (reversed)", "Agreeableness3",
        "Agreeableness4 (reversed)", "Conscientiousness1", "Conscientiousness2",
        "Conscientiousness3 (reversed)", "Conscientiousness4 (reversed)", "Neuroticism1",
        "Neuroticism2 (reversed)", "Neuroticism3", "Neuroticism4 (reversed)",
        "Openness1", "Openness2 (reversed)", "Openness3 (reversed)", "Openness4 (reversed)",
        "Narcissism1", "Narcissism2", "Honesty-Humility1 (reversed)",
        "Honesty-Humility2 (reversed"
      ),
    `Description / Text` = 
      c("It is OK if some groups have more of a chance in life than others",
        "Inferior groups should stay in their place",
        "To get ahead in life, it is sometimes okay to step on other groups",
        "We should have increased social equality",
        "It would be good if groups could be equal",
        "We should do what we can to equalise conditions for different groups",
        "It is always better to trust the judgment of the proper authorities in government and religion than to listen to the noisy rabble-rousers in our society who are trying to create doubt in people's minds",
        "It would be best for everyone if the proper authorities censored magazines so that people could not get their hands on trashy and disgusting material",
        "Our country will be destroyed some day if we do not smash the perversions eating away at our moral fibre and traditional beliefs",
        "People should pay less attention to The Bible and other old traditional forms of religious guidance, and instead develop their own personal standards of what is moral and immoral",
        "Atheists and others who have rebelled against established religions are no doubt every bit as good and virtuous as those who attend church regularly",
        "Some of the best people in our country are those who are challenging our government, criticizing religion, and ignoring the 'normal way' things are supposed to be done",
        "Redistributing money and wealth more evenly among a larger percentage of the people in New Zealand through heavy taxes on the rich",
        "If incomes were more equal, people would be less motivated to work hard",
        "Level of support for The National Party",
        "What is your date of birth?",
        "What is your gender? (open-ended)",
        "Which ethnic group do you belong to? (NZ census question)",
        "NZ Reg (0-10 education ordinal rank)",
        "NZSEI13 (NZ Socio-economic index)",
        "Deprivation score 2013 (for Meshblock)",
        "Do you identify with a religion and/or spiritual group?",
        "Am the life of the party",
        "Don't talk a lot",
        "Keep in the background",
        "Talk to a lot of different people at parties",
        "Sympathize with others' feelings",
        "Am not interested in other people's problems",
        "Feel others' emotions",
        "Am not really interested in others",
        "Get chores done right away",
        "Like order",
        "Make a mess of things",
        "Often forget to put things back in their proper place",
        "Have frequent mood swings",
        "Am relaxed most of the time",
        "Get upset easily",
        "Seldom feel blue",
        "Have a vivid imagination",
        "Have difficulty understanding abstract ideas",
        "Do not have a good imagination",
        "Am not interested in abstract ideas",
        "Feel entitled to more of everything",
        "Deserve more things in life",
        "Would like to be seen driving around in a very expensive car",
        "Would get a lot of pleasure from owning expensive lucury goods"
      ),
    Wave = c(rep("10 - 11", 6), rep("10", 6), rep("10 - 11", 3), rep("10", 31))
  )
}
